version: '3.7'

services:
  tor_server:
    image: ghcr.io/getumbrel/tor:0.4.9.9@sha256:3580be8f7f080c10b53889d64f7074f0f4f823b479bacaf229e7631ab7571ef1
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${TOR_ENTRYPOINT_SCRIPT}:/umbrel/entrypoint.sh
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: '/tmp'
      HS_DIR: '${TOR_HS_APP_DIR}'
      HS_PORTS: '${TOR_HS_PORTS}'
    entrypoint: '/umbrel/entrypoint.sh'
