import crypto from 'node:crypto'

import {expect, test, beforeEach, beforeAll, afterAll} from 'vitest'

import {createTestVm} from '../test-utilities/create-test-umbreld.js'

let umbreld: Awaited<ReturnType<typeof createTestVm>>

beforeAll(async () => {
	umbreld = await createTestVm({device: 'umbrel-home'})
	await umbreld.vm.powerOn()
	await umbreld.registerAndLogin()
})

afterAll(async () => {
	await umbreld.cleanup()
})

beforeEach(async () => {
	// Clean up thumbnails directory (owned by umbreld running as root, so the
	// regular ssh user can't write there)
	await umbreld.vm.sshAsRoot('rm -rf /home/umbrel/umbrel/thumbnails/* || true')
})

test('GET /api/files/thumbnail/:thumbnail throws unauthorized error without cookie', async () => {
	const error = await umbreld.unauthenticatedApi.get('files/thumbnail/12345.webp').catch((error) => error)
	expect(error).toBeInstanceOf(Error)
	expect(error.response.statusCode).toBe(401)
	expect(error.response.body).toMatchObject({error: 'unauthorized'})
})

test('GET /api/files/thumbnail/:thumbnail throws 404 error without a thumbnail path', async () => {
	const error = await umbreld.api.get('files/thumbnail/').catch((error) => error)
	expect(error).toBeInstanceOf(Error)
	expect(error.response.statusCode).toBe(404)
})

test('GET /api/files/thumbnail/:thumbnail throws 404 error when thumbnail does not exist', async () => {
	// Generate a valid sha256 hash that doesn't exist in the system
	const validHash = crypto.createHash('sha256').update('nonexistent-file').digest('hex')
	const error = await umbreld.api.get(`files/thumbnail/${validHash}.webp`).catch((error) => error)
	expect(error).toBeInstanceOf(Error)
	// When using express.static, we get a 404 HTML page
	expect(error.response.statusCode).toBe(404)
})

test('GET /api/files/thumbnail/:thumbnail serves a thumbnail with valid hash and correct cache headers', async () => {
	// Seed a mock thumbnail file with a valid hex hash name into the thumbnails
	// directory. Thumbnails are generated by umbreld internally so there's no
	// product surface to place one with known content — the static file server
	// under test doesn't care about the bytes, only the path.
	const hash = crypto.createHash('sha256').update('test-thumbnail-data').digest('hex')
	const thumbnailData = 'mock thumbnail bytes'
	await umbreld.vm.sshAsRoot(
		`mkdir -p /home/umbrel/umbrel/thumbnails && printf '%s' '${thumbnailData}' > /home/umbrel/umbrel/thumbnails/${hash}.webp`,
	)

	// Request the thumbnail through the API
	// Use responseType: 'buffer' to override the default behaviour and get binary data instead of trying to parse as JSON
	const response = await umbreld.api.get(`files/thumbnail/${hash}.webp`, {responseType: 'buffer'})

	// Assert the response is correct
	expect(response.statusCode).toBe(200)

	// Check that we get cache headers
	expect(response.headers['cache-control']).toBe('public, max-age=31536000, immutable')

	// Check content type header is for webp images
	expect(response.headers['content-type']).toBe('image/webp')

	// Verify the response body matches the seeded thumbnail content
	expect(Buffer.from(response.body as Buffer).toString()).toBe(thumbnailData)
})
